default_language_version:
  python: python3.7
default_stages: [commit, push]
repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.1.4
  hooks:
  - id: isort
